### ISSUE TITLE
Nothing works :/

### ISSUE THREAD

**Issue by braedonrogers99** [nathanaccidentally/Dock#3]
iPhone 6s, 10.2 - currently listening to Hotel California (if it helps)

**Comment by braedonrogers99** [comment]
Hmm. Seems like all of your tweaks I've tested this far need two to three resprings to get things to work.

**Comment by nathanaccidentally** [comment]
Do the corners round at all? If it isn't floating it's a known issue.

And yeah, I manually load my prefs no it might be a little slower to apply. I will add Cephei next version for pref loading.

EDIT: Here is Cephei. http://cydia.saurik.com/package/ws.hbang.common/

**Comment by braedonrogers99** [comment]
Yes, everything that's supposed to work does now.

**Comment by nathanaccidentally** [comment]
Yay! Are you using CF2?

**Comment by braedonrogers99** [comment]
Nope.

**Comment by nathanaccidentally** [comment]
That is probably why. I am looking into this but CoolStar isn't helping me much.

**Comment by nathanaccidentally** [comment]
I'm closing this issue for now.
