### ISSUE TITLE
more of a question than an issue but what's this made in?

### ISSUE THREAD

**Issue by ghost** [nathanaccidentally/Dock#6]
what ide should i use (probably xcode but asking anyway)? how do I compile?

**Comment by nathanaccidentally** [comment]
You don't need to use an IDE to compile Dock and most other Jailbreak tweaks for that matter. All you need is [Theos](https://github.com/theos/theos) (which requires Xcode) and a plain text editor.

Then you can easily build the package in terminal with 'make package'.

**Comment by ghost** [comment]
Thank you! Side question before I close the issue, where should I start learning how to make tweaks? What languages/other things should I read up on?

**Comment by nathanaccidentally** [comment]
I just made a few really basic apps using Xcode to kinda get a rough idea, then I used google and/or the people on Discord and Reddit whenever I got stuck.
